/* =====================================================
   auth.js — Authentication module for {{VENUE_NAME_EN}}
   Generated by VenueKit
===================================================== */

const Auth = {
    currentUser: null,
    currentPlayer: null,
    _initialized: false,
    _dropdownListenerAdded: false,

    async init() {
        const { data: { session } } = await db.auth.getSession();
        if (session) {
            this.currentUser = session.user;
            await this.loadPlayer();
        }

        db.auth.onAuthStateChange(async (event, session) => {
            if (event === 'SIGNED_IN' && session) {
                this.currentUser = session.user;
                await this.loadPlayer();
                this.updateUI();
                await db.from('players').update({ last_login: new Date().toISOString() }).eq('id', session.user.id);
            } else if (event === 'SIGNED_OUT') {
                this.currentUser = null;
                this.currentPlayer = null;
                this.updateUI();
            }
        });

        this._initialized = true;
        this.updateUI();
    },

    async loadPlayer() {
        if (!this.currentUser) return;
        const { data } = await db.from('players').select('*').eq('id', this.currentUser.id).single();
        this.currentPlayer = data;
    },

    {{#if google_auth}}
    async signInWithGoogle() {
        const { error } = await db.auth.signInWithOAuth({
            provider: 'google',
            options: { redirectTo: Utils.getBaseUrl() + 'index.html' }
        });
        if (error) {
            Utils.showToast('שגיאה בהתחברות עם Google', 'error');
            console.error('Google auth error:', error);
        }
    },
    {{/if}}

    {{#if facebook_auth}}
    async signInWithFacebook() {
        const { error } = await db.auth.signInWithOAuth({
            provider: 'facebook',
            options: { redirectTo: Utils.getBaseUrl() + 'index.html' }
        });
        if (error) {
            Utils.showToast('שגיאה בהתחברות עם Facebook', 'error');
            console.error('Facebook auth error:', error);
        }
    },
    {{/if}}

    async signOut() {
        const { error } = await db.auth.signOut();
        if (error) {
            Utils.showToast('שגיאה בהתנתקות', 'error');
        } else {
            window.location.href = Utils.getBasePath() + 'index.html';
        }
    },

    isLoggedIn() {
        return !!this.currentUser;
    },

    isAdmin() {
        return this.currentPlayer?.is_admin === true;
    },

    requireLogin() {
        if (!this.isLoggedIn()) {
            const returnUrl = encodeURIComponent(window.location.pathname + window.location.search);
            window.location.href = Utils.getBasePath() + `login.html?return=${returnUrl}`;
            return false;
        }
        return true;
    },

    requireAdmin() {
        if (!this.isLoggedIn() || !this.isAdmin()) {
            window.location.href = Utils.getBasePath() + 'index.html';
            return false;
        }
        return true;
    },

    updateUI() {
        const authNav = document.getElementById('auth-nav');
        if (authNav) {
            if (this.isLoggedIn()) {
                const avatar = this.currentPlayer?.avatar_url || this.currentUser?.user_metadata?.avatar_url || '';
                const name = this.currentPlayer?.full_name || this.currentUser?.user_metadata?.full_name || 'שחקן';
                authNav.innerHTML = `
                    <div class="user-menu">
                        <button class="user-menu-btn" onclick="document.querySelector('.user-dropdown').classList.toggle('show')">
                            ${avatar ? `<img src="${Utils.sanitizeUrl(avatar)}" alt="${Utils.escapeHtml(name)}" class="user-avatar">` : '<span class="user-avatar-placeholder">👤</span>'}
                            <span class="user-name">${Utils.escapeHtml(name)}</span>
                        </button>
                        <div class="user-dropdown">
                            <a href="${Utils.getBasePath()}profile.html">הפרופיל שלי</a>
                            ${this.isAdmin() ? `<a href="${Utils.getBasePath()}admin/index.html">פנל ניהול</a>` : ''}
                            <button onclick="Auth.signOut()">התנתק</button>
                        </div>
                    </div>
                `;
            } else {
                authNav.innerHTML = `<a href="${Utils.getBasePath()}login.html" class="btn btn-gold btn-sm">התחבר</a>`;
            }
        }

        const adminLink = document.getElementById('admin-nav-link');
        if (adminLink) {
            adminLink.style.display = this.isAdmin() ? '' : 'none';
        }

        if (!this._dropdownListenerAdded) {
            this._dropdownListenerAdded = true;
            document.addEventListener('click', (e) => {
                if (!e.target.closest('.user-menu')) {
                    document.querySelectorAll('.user-dropdown.show').forEach(d => d.classList.remove('show'));
                }
            });
        }
    }
};

document.addEventListener('DOMContentLoaded', () => Auth.init());
window.Auth = Auth;
