/* =====================================================
   cookie-consent.js — Cookie consent banner
   Generated by VenueKit for: {{VENUE_NAME_EN}}
===================================================== */

class CookieConsent extends HTMLElement {
  connectedCallback() {
    if (localStorage.getItem("{{VENUE_NAME_EN}}-cookie-consent")) return;

    this.innerHTML = `
      <div id="cookie-banner" role="dialog" aria-label="הסכמה לעוגיות" dir="rtl"
           style="position:fixed;bottom:0;left:0;right:0;z-index:9998;background:var(--bg-card, #0f1a2e);border-top:1.5px solid rgba(232,184,41,.15);padding:16px 20px;font-family:'{{FONT_HEBREW}}',sans-serif;direction:rtl;transform:translateY(100%);transition:transform .4s ease">
        <div style="max-width:900px;margin:0 auto;display:flex;flex-wrap:wrap;align-items:center;gap:12px;justify-content:space-between">
          <div style="flex:1;min-width:240px">
            <p style="font-size:13px;color:#f1f5f9;margin:0 0 4px;font-weight:600">האתר משתמש בעוגיות (Cookies)</p>
            <p style="font-size:12px;color:#94a3b8;margin:0;line-height:1.6">
              אנו משתמשים בעוגיות לשיפור חוויית הגלישה וניתוח שימוש.
            </p>
          </div>
          <div style="display:flex;gap:8px;flex-shrink:0">
            <button id="cookie-accept" style="padding:10px 24px;border-radius:10px;background:var(--secondary, #e8b829);color:#080d1a;font-weight:700;font-size:13px;border:none;cursor:pointer;font-family:'{{FONT_HEBREW}}',sans-serif;transition:background .2s">
              מאשר
            </button>
            <button id="cookie-reject" style="padding:10px 24px;border-radius:10px;background:rgba(255,255,255,.06);color:#f1f5f9;font-weight:600;font-size:13px;border:1px solid rgba(255,255,255,.1);cursor:pointer;font-family:'{{FONT_HEBREW}}',sans-serif;transition:background .2s">
              דחייה
            </button>
          </div>
        </div>
      </div>`;

    const banner = this.querySelector("#cookie-banner");
    requestAnimationFrame(() => {
      setTimeout(() => { banner.style.transform = "translateY(0)"; }, 500);
    });

    this.querySelector("#cookie-accept").addEventListener("click", () => {
      localStorage.setItem("{{VENUE_NAME_EN}}-cookie-consent", "accepted");
      this._dismiss(banner);
    });

    this.querySelector("#cookie-reject").addEventListener("click", () => {
      localStorage.setItem("{{VENUE_NAME_EN}}-cookie-consent", "rejected");
      this._dismiss(banner);
    });
  }

  _dismiss(banner) {
    banner.style.transform = "translateY(100%)";
    setTimeout(() => banner.remove(), 400);
  }
}

customElements.define("cookie-consent", CookieConsent);
