/* =====================================================
   errorHandler.js — Global error catcher -> Supabase
   Generated by VenueKit for: {{VENUE_NAME_EN}}
===================================================== */

(function () {
  const SUPABASE_URL = '{{SUPABASE_URL}}';
  const SUPABASE_ANON_KEY = '{{SUPABASE_KEY}}';
  const ENDPOINT = `${SUPABASE_URL}/rest/v1/js_errors`;

  let errorCount = 0;
  const MAX_ERRORS = 5;

  function sendError(data) {
    if (errorCount >= MAX_ERRORS) return;
    errorCount++;

    const payload = {
      message: String(data.message || '').slice(0, 500),
      source: String(data.source || '').slice(0, 300),
      line: data.line || null,
      col: data.col || null,
      stack: String(data.stack || '').slice(0, 2000),
      page: location.pathname,
      user_agent: navigator.userAgent.slice(0, 300),
      timestamp: new Date().toISOString()
    };

    fetch(ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_ANON_KEY,
        'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
        'Prefer': 'return=minimal'
      },
      body: JSON.stringify(payload),
      keepalive: true
    }).catch(() => {});
  }

  window.addEventListener('error', function (e) {
    if (!e.filename || e.filename === '') return;
    if (e.filename.includes('extension://')) return;
    sendError({
      message: e.message,
      source: e.filename,
      line: e.lineno,
      col: e.colno,
      stack: e.error?.stack || ''
    });
  });

  window.addEventListener('unhandledrejection', function (e) {
    const reason = e.reason;
    sendError({
      message: reason?.message || String(reason).slice(0, 500),
      source: 'unhandledrejection',
      stack: reason?.stack || ''
    });
  });
})();
