/* =====================================================
   supabase-config.js — Supabase client initialization
   Generated by VenueKit for: {{VENUE_NAME_EN}}
===================================================== */

const SUPABASE_URL = '{{SUPABASE_URL}}';
const SUPABASE_ANON_KEY = '{{SUPABASE_KEY}}';

window.db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
