/* =====================================================
   utils.js — Shared utilities for {{VENUE_NAME_EN}}
   Generated by VenueKit
===================================================== */

const Utils = {
    getBasePath() {
        return window.location.pathname.includes('/admin/') ? '../' : './';
    },

    getBaseUrl() {
        const path = window.location.pathname;
        const adminIdx = path.indexOf('/admin/');
        if (adminIdx !== -1) return window.location.origin + path.substring(0, adminIdx + 1);
        return window.location.origin + path.substring(0, path.lastIndexOf('/') + 1);
    },

    formatDateHebrew(dateStr) {
        const date = new Date(typeof dateStr === 'string' && dateStr.length === 10 ? dateStr + 'T12:00:00' : dateStr);
        const days = ['יום ראשון', 'יום שני', 'יום שלישי', 'יום רביעי', 'יום חמישי', 'יום שישי', 'שבת'];
        const months = ['ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני', 'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר'];
        return `${days[date.getDay()]}, ${date.getDate()} ב${months[date.getMonth()]} ${date.getFullYear()}`;
    },

    formatDateShort(dateStr) {
        const date = new Date(typeof dateStr === 'string' && dateStr.length === 10 ? dateStr + 'T12:00:00' : dateStr);
        return `${String(date.getDate()).padStart(2, '0')}/${String(date.getMonth() + 1).padStart(2, '0')}/${date.getFullYear()}`;
    },

    formatTime(timeStr) {
        if (!timeStr) return '';
        return timeStr.substring(0, 5);
    },

    formatCurrency(amount) {
        return `{{CURRENCY}}${(amount || 0).toLocaleString('he-IL')}`;
    },

    formatNumber(num) {
        return (num || 0).toLocaleString('he-IL');
    },

    getCountdown(targetDate, targetTime) {
        const t = (targetTime || '{{WEEKLY_TIME}}').substring(0, 5);
        const target = new Date(`${targetDate}T${t}:00`);
        const now = new Date();
        const diff = target - now;

        if (diff <= 0) return { days: 0, hours: 0, minutes: 0, seconds: 0, expired: true };

        return {
            days: Math.floor(diff / (1000 * 60 * 60 * 24)),
            hours: Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)),
            minutes: Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60)),
            seconds: Math.floor((diff % (1000 * 60)) / 1000),
            expired: false
        };
    },

    isDeadlinePassed(date, deadline) {
        const t = (deadline || '17:00').substring(0, 5);
        const deadlineDate = new Date(`${date}T${t}:00`);
        return new Date() > deadlineDate;
    },

    isEarlyBird(date, deadline) {
        return !this.isDeadlinePassed(date, deadline);
    },

    getStatusBadge(status) {
        const badges = {
            upcoming: '<span class="badge badge-success">קרוב</span>',
            active: '<span class="badge badge-primary">פעיל</span>',
            completed: '<span class="badge badge-muted">הסתיים</span>',
            cancelled: '<span class="badge badge-danger">בוטל</span>'
        };
        return badges[status] || '';
    },

    showToast(message, type = 'info') {
        const existing = document.querySelector('.toast');
        if (existing) existing.remove();

        const toast = document.createElement('div');
        toast.className = `toast toast-${type}`;
        toast.textContent = message;
        document.body.appendChild(toast);

        requestAnimationFrame(() => toast.classList.add('show'));

        setTimeout(() => {
            toast.classList.remove('show');
            setTimeout(() => toast.remove(), 300);
        }, 3000);
    },

    showLoading(container) {
        if (typeof container === 'string') container = document.querySelector(container);
        if (!container) return;
        container.innerHTML = '<div style="text-align:center;padding:2rem;color:var(--text-muted)">טוען...</div>';
    },

    getParam(name) {
        return new URLSearchParams(window.location.search).get(name);
    },

    debounce(func, wait) {
        let timeout;
        return function executedFunction(...args) {
            clearTimeout(timeout);
            timeout = setTimeout(() => func.apply(this, args), wait);
        };
    },

    escapeHtml(text) {
        if (text == null) return '';
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    },

    sanitizeUrl(url) {
        if (!url) return '';
        try {
            const parsed = new URL(url);
            if (parsed.protocol === 'https:' || parsed.protocol === 'http:') return this.escapeHtml(url);
        } catch {}
        return '';
    },

    {{#if csv_export}}
    exportToCSV(rows, headers, filename) {
        const keys = Object.keys(headers);
        const headerLine = keys.map(k => headers[k]).join(',');
        const csvRows = rows.map(row =>
            keys.map(k => {
                let val = row[k] ?? '';
                val = String(val);
                if (val.includes(',') || val.includes('\n') || val.includes('"')) {
                    val = '"' + val.replace(/"/g, '""') + '"';
                }
                return val;
            }).join(',')
        );
        const csv = '\uFEFF' + headerLine + '\n' + csvRows.join('\n');
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename || 'export.csv';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    },
    {{/if}}
};

window.Utils = Utils;

// Navbar scroll behavior
(function() {
    const navbar = document.querySelector('.navbar');
    if (!navbar) return;
    const isHeroPage = document.querySelector('.hero-page');
    function handleScroll() {
        navbar.classList.toggle('scrolled', window.scrollY > 50 || !isHeroPage);
    }
    if (!isHeroPage) navbar.classList.add('scrolled');
    window.addEventListener('scroll', handleScroll, { passive: true });
    handleScroll();
})();
